"""Generates a Scala source whose only method is too large to instrument."""

# `count` compiles to roughly 11 bytes of bytecode per `if`, so 4000 branches
# put it around 44KB: comfortably under the JVM's 64KB per-method limit, and
# comfortably over it once JaCoCo adds two probes worth about 12 bytes to each
# branch.
_BRANCHES = 4000

def oversized_method_source():
    """Returns the lines of a class with a single, nearly-64KB method."""
    return [
        "package coverage_oversized_method",
        "",
        "// Generated by //test/coverage_oversized_method:oversized_method_source.",
        "//",
        "// `count` compiles to just under the JVM's 64KB per-method bytecode limit, so",
        "// JaCoCo's probes push it over and ASM refuses to write the instrumented class.",
        "class OversizedMethod {",
        "  def count(flag: Boolean): Int = {",
        "    var acc = 0",
    ] + [
        "    if (flag) acc += 1"
        for _ in range(_BRANCHES)
    ] + [
        "    acc",
        "  }",
        "}",
    ]
