"""Fetches a real external consumer as a Bazel-native external repo."""

def _downstream_consumer_repository_impl(repository_ctx):
    remote = repository_ctx.attr.remote
    commit = repository_ctx.attr.commit

    repository_ctx.execute(["git", "init", "--quiet", "."])
    repository_ctx.execute(["git", "remote", "add", "origin", remote])
    result = repository_ctx.execute(
        ["git", "fetch", "--quiet", "--depth", "1", "origin", commit],
        timeout = 20,
    )
    if result.return_code != 0:
        fail("git fetch failed for %s @ %s:\n%s" % (remote, commit, result.stderr))
    result = repository_ctx.execute(["git", "checkout", "--quiet", "FETCH_HEAD"])
    if result.return_code != 0:
        fail("git checkout failed for %s @ %s:\n%s" % (remote, commit, result.stderr))

    # The whole point: resolve *this* checkout's absolute path via repository_ctx,
    # instead of a caller having to know/compute it in bash.
    rules_scala_dir = str(repository_ctx.path(Label("@rules_scala//:MODULE.bazel")).dirname)

    module_bazel = repository_ctx.path("MODULE.bazel")
    existing = repository_ctx.read(module_bazel)
    repository_ctx.file(module_bazel, existing + '''

local_path_override(
    module_name = "rules_scala",
    path = "{rules_scala_dir}",
)
'''.format(rules_scala_dir = rules_scala_dir))

    for patch in repository_ctx.attr.patches:
        repository_ctx.patch(patch, strip = 1)

    # A downstream_test's `sh_test` needs a real Bazel dependency edge on this
    # repo, so Bazel fetches it before the test runs -- but referencing any
    # label under the consumer's own (real) BUILD files would make Bazel load
    # them, which fails on whatever `bazel_dep`s the consumer declares that
    # aren't in *our* module graph (e.g. joern's `aspect_rules_lint`). This
    # marker package is generated by us, lives alongside the consumer's real
    # files without touching them, and is the only thing `downstream_test`
    # ever references (as a `data` dependency, not a `load()` -- see
    # test/community_build/BUILD for why that distinction matters here).
    repository_ctx.file(
        "_bazel_native_marker/BUILD",
        'exports_files(["marker.txt"])\n',
    )
    repository_ctx.file("_bazel_native_marker/marker.txt", commit + "\n")

_downstream_consumer_repository = repository_rule(
    implementation = _downstream_consumer_repository_impl,
    attrs = {
        "remote": attr.string(mandatory = True),
        "commit": attr.string(mandatory = True),
        "patches": attr.label_list(default = []),
    },
)

def _downstream_consumers_impl(module_ctx):
    for mod in module_ctx.modules:
        for consumer in mod.tags.consumer:
            _downstream_consumer_repository(
                name = consumer.name,
                remote = consumer.remote,
                commit = consumer.commit,
                patches = consumer.patches,
            )

downstream_consumers = module_extension(
    implementation = _downstream_consumers_impl,
    tag_classes = {
        "consumer": tag_class(attrs = {
            "name": attr.string(mandatory = True),
            "remote": attr.string(mandatory = True),
            "commit": attr.string(mandatory = True),
            "patches": attr.label_list(default = []),
        }),
    },
)
