"""Fetches a real external consumer as a Bazel-native external repo."""

def _downstream_consumer_repository_impl(repository_ctx):
    remote = repository_ctx.attr.remote
    commit = repository_ctx.attr.commit

    repository_ctx.execute(["git", "init", "--quiet", "."])
    repository_ctx.execute(["git", "remote", "add", "origin", remote])
    result = repository_ctx.execute(
        ["git", "fetch", "--quiet", "--depth", "1", "origin", commit],
        timeout = 600,
    )
    if result.return_code != 0:
        fail("git fetch failed for %s @ %s:\n%s" % (remote, commit, result.stderr))
    result = repository_ctx.execute(["git", "checkout", "--quiet", "FETCH_HEAD"])
    if result.return_code != 0:
        fail("git checkout failed for %s @ %s:\n%s" % (remote, commit, result.stderr))

    # The whole point: resolve *this* checkout's absolute path via repository_ctx,
    # instead of a caller having to know/compute it in bash.
    rules_scala_dir = str(repository_ctx.path(Label("@rules_scala//:MODULE.bazel")).dirname)

    module_bazel = repository_ctx.path("MODULE.bazel")
    existing = repository_ctx.read(module_bazel)
    repository_ctx.file(module_bazel, existing + '''

local_path_override(
    module_name = "rules_scala",
    path = "{rules_scala_dir}",
)
'''.format(rules_scala_dir = rules_scala_dir))

    for cmd in repository_ctx.attr.patch_cmds:
        result = repository_ctx.execute(["bash", "-c", cmd])
        if result.return_code != 0:
            fail("patch_cmd failed: %s\n%s" % (cmd, result.stderr))

    # A downstream_test's `sh_test` needs a real Bazel dependency edge on this
    # repo, so Bazel fetches it before the test runs -- but referencing any
    # label under the consumer's own (real) BUILD files would make Bazel load
    # them, which fails on whatever `bazel_dep`s the consumer declares that
    # aren't in *our* module graph (e.g. joern's `aspect_rules_lint`). This
    # marker package is generated by us, lives alongside the consumer's real
    # files without touching them, and is the only thing `downstream_test`
    # ever references.
    #
    # Also exposes `scala_version` as a loadable constant (version.bzl), so
    # the pin declared once here in MODULE.bazel is the only place it's
    # written down -- test/community_build/BUILD loads it instead of
    # repeating the same version as a separate literal.
    repository_ctx.file(
        "_bazel_native_marker/BUILD",
        'exports_files(["marker.txt", "version.bzl"])\n',
    )
    repository_ctx.file("_bazel_native_marker/marker.txt", commit + "\n")
    repository_ctx.file(
        "_bazel_native_marker/version.bzl",
        'SCALA_VERSION = "{}"\n'.format(repository_ctx.attr.scala_version),
    )

_downstream_consumer_repository = repository_rule(
    implementation = _downstream_consumer_repository_impl,
    attrs = {
        "remote": attr.string(mandatory = True),
        "commit": attr.string(mandatory = True),
        "scala_version": attr.string(mandatory = True),
        "patch_cmds": attr.string_list(default = []),
    },
)

# databricks/dicer pins `protobuf` to an exact version (with a local patch,
# for an unrelated legacy Python-toolchain registration bug) via its own
# root-module `single_version_override`. `single_version_override` is only
# honored from the *root* module of a build -- and once we build from inside
# dicer's checkout, dicer's own MODULE.bazel *is* the root, so this
# checkout's own `single_version_override(protobuf, "33.5")` is silently
# ignored in favor of dicer's "30.2". The scalapb/protoc tooling
# rules_scala's `scala_proto` extension bundles is generated against 33.5's
# gencode, so building against 30.2's older runtime fails hard at codegen
# time. Fix: take over dicer's override, bumping it to what this checkout
# expects and dropping its now-inapplicable patch.
_DICER_PROTOBUF_OVERRIDE_PATCH_CMD = """awk '
  /^single_version_override\\($/ { buffering = 1; n = 0; buf[n++] = $0; next }
  buffering {
    buf[n++] = $0
    if ($0 == ")") {
      is_protobuf = 0
      for (i = 0; i < n; i++) if (buf[i] ~ /module_name = "protobuf"/) is_protobuf = 1
      if (is_protobuf) {
        print "single_version_override("
        print "    module_name = \\"protobuf\\","
        print "    version = \\"33.5\\","
        print ")"
      } else {
        for (i = 0; i < n; i++) print buf[i]
      }
      buffering = 0
      next
    }
    next
  }
  { print }
' MODULE.bazel > MODULE.bazel.tmp && mv MODULE.bazel.tmp MODULE.bazel"""

# Per-consumer patch_cmds, keyed by the name each is declared under in
# MODULE.bazel -- keeps consumer-specific quirks (and the shell one-liners
# implementing them) out of MODULE.bazel entirely, since `load()` isn't
# allowed there and it has no other way to pull in a value defined here.
_CONSUMER_PATCH_CMDS = {
    "dicer": [
        _DICER_PROTOBUF_OVERRIDE_PATCH_CMD,
        # The awk pass above exits 0 even when its pattern matches nothing --
        # if dicer ever reformats its override block, the rewrite silently
        # no-ops and the failure shows up much later as an opaque protobuf
        # gencode/runtime mismatch inside the nested build. Assert the bump
        # actually landed, so a drifted upstream fails right here instead.
        '''grep -q 'version = "33.5"' MODULE.bazel''',
    ],
}

def _downstream_consumers_impl(module_ctx):
    for mod in module_ctx.modules:
        for consumer in mod.tags.consumer:
            _downstream_consumer_repository(
                name = consumer.name,
                remote = consumer.remote,
                commit = consumer.commit,
                scala_version = consumer.scala_version,
                patch_cmds = _CONSUMER_PATCH_CMDS.get(consumer.name, []),
            )

downstream_consumers = module_extension(
    implementation = _downstream_consumers_impl,
    tag_classes = {
        "consumer": tag_class(attrs = {
            "name": attr.string(mandatory = True),
            "remote": attr.string(mandatory = True),
            "commit": attr.string(mandatory = True),
            "scala_version": attr.string(mandatory = True),
        }),
    },
)
