load("//scala:scala.bzl", "scala_specs2_junit_test")

scala_specs2_junit_test(
    name = "specs2_failing_test",
    size = "small",
    srcs = [
        "specs2/FailingTest.scala",
        "specs2/SuiteWithOneFailingTest.scala",
    ],
    suffixes = ["Test"],
)
