dist: xenial
sudo: required
language: sh
osx_image: xcode10.1

addons:
  apt:
    packages:
    - libxml2-utils

cache:
    directories:
     - .bazel_cache
     - ~/.bazel_binaries

os:
  - linux
  - osx
  - windows

env:
  # Linting is broken. Disable until fixed.
  # See https://github.com/bazelbuild/rules_scala/pull/622
  # we want to test the last release
  #- V=0.16.1 TEST_SCRIPT=test_lint.sh
  - TEST_SCRIPT=test_rules_scala
  #- V=0.14.1 TEST_SCRIPT=test_intellij_aspect.sh
  - TEST_SCRIPT=test_reproducibility


before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "windows" ]]; then
      choco install jdk8 -params 'installdir=c:\\java8'
      choco install bazel --version 0.28.0
    fi
  - cat .bazelrc.travis >> .bazelrc

script:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "windows" ]]; then
      powershell -Command 'Set-ExecutionPolicy RemoteSigned -scope CurrentUser'
      BAZEL_VERSION=host powershell -File ./${TEST_SCRIPT}.ps1
    else
      bash ./${TEST_SCRIPT}.sh ci
    fi
