dist: xenial
sudo: required
language: sh
osx_image: xcode10.1

cache:
  directories:
    - ~/.bazel_binaries
    - .bazel_cache

os:
  - linux
  - osx
  - windows

_linux: &linux
  os: linux
_osx: &osx
  os: osx
  osx_image: xcode10.1
_windows: &windows
  os: windows
  before_install:
    - |
      if [[ "${TRAVIS_OS_NAME}" == "windows" ]]; then
        choco install jdk8 -params 'installdir=c:\\java8'
        choco install bazel --version ${V}
      fi

jobs:
  include:
    # test_rules_scala
    - stage: test
      <<: *linux
      env: TEST_SCRIPT=test_rules_scala
    - <<: *osx
      env: TEST_SCRIPT=test_rules_scala
    - <<: *windows
      env: TEST_SCRIPT=test_rules_scala
    # test_reproducibility
    - stage: test_reproducibility
      <<: *linux
      env: TEST_SCRIPT=test_reproducibility
    - <<: *osx
      env: TEST_SCRIPT=test_reproducibility
    - <<: *windows
      env: TEST_SCRIPT=test_reproducibility

before_install:
  - cat .bazelrc.travis >> .bazelrc

script:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "windows" ]]; then
      powershell -Command 'Set-ExecutionPolicy RemoteSigned -scope CurrentUser'
      powershell -File ./${TEST_SCRIPT}.ps1
    else
      bash ./${TEST_SCRIPT}.sh ci
    fi
