#!/usr/bin/env bash
#
# Script to analyze non-determinism in -docs.jar files generated by maven_export
# Run from the rules_scala root directory
#

set -e

TARGET="//test/scala_export:external_dep-docs"
JAR_PATH="bazel-bin/test/scala_export/external_dep-docs.jar"

echo "=== Analyzing non-determinism in $TARGET ==="
echo ""

# Create temp directories for extraction
DIR1=$(mktemp -d -t docs_jar_build1-XXXXXXXXXX)
DIR2=$(mktemp -d -t docs_jar_build2-XXXXXXXXXX)
CACHE1=$(mktemp -d -t cache1-XXXXXXXXXX)
CACHE2=$(mktemp -d -t cache2-XXXXXXXXXX)

cleanup() {
    rm -rf "$DIR1" "$DIR2" "$CACHE1" "$CACHE2"
}
trap cleanup EXIT

echo ">>> Build 1"
bazel clean 2>/dev/null
bazel build --disk_cache="$CACHE1" "$TARGET" 2>/dev/null
cat "$JAR_PATH" > "$DIR1/docs.jar"
(cd "$DIR1" && unzip -o -q docs.jar && rm docs.jar)

echo ">>> Build 2 (after clean and sleep)"
bazel clean 2>/dev/null
sleep 5  # Ensure different timestamps
bazel build --disk_cache="$CACHE2" "$TARGET" 2>/dev/null
cat "$JAR_PATH" > "$DIR2/docs.jar"
(cd "$DIR2" && unzip -o -q docs.jar && rm docs.jar)

echo ""
echo "=== Comparing jar contents ==="
echo ""

# Compare file lists
echo "--- Files only in build 1:"
diff <(cd "$DIR1" && find . -type f | sort) <(cd "$DIR2" && find . -type f | sort) | grep "^<" || echo "(none)"

echo ""
echo "--- Files only in build 2:"
diff <(cd "$DIR1" && find . -type f | sort) <(cd "$DIR2" && find . -type f | sort) | grep "^>" || echo "(none)"

echo ""
echo "--- Files with different content:"
DIFF_FILES=()
while IFS= read -r file; do
    if [ -f "$DIR1/$file" ] && [ -f "$DIR2/$file" ]; then
        if ! cmp -s "$DIR1/$file" "$DIR2/$file"; then
            DIFF_FILES+=("$file")
            echo "  $file"
        fi
    fi
done < <(cd "$DIR1" && find . -type f | sort)

echo ""
echo "=== Showing differences in changed files ==="
echo ""

for file in "${DIFF_FILES[@]}"; do
    echo ">>> Diff for: $file"
    echo "-------------------------------------------"
    
    if [[ "$file" == *.zip ]]; then
        # These are zip files - extract and compare
        ZIPDIR1=$(mktemp -d)
        ZIPDIR2=$(mktemp -d)
        
        # Extract zip contents
        unzip -o -q "$DIR1/$file" -d "$ZIPDIR1" 2>/dev/null || true
        unzip -o -q "$DIR2/$file" -d "$ZIPDIR2" 2>/dev/null || true
        
        # List what we extracted
        echo "  Extracted files from zip:"
        (cd "$ZIPDIR1" && find . -type f) || true
        
        # Compare extracted contents
        found_diff=false
        for zfile in $(cd "$ZIPDIR1" && find . -type f 2>/dev/null); do
            if [ -f "$ZIPDIR1/$zfile" ] && [ -f "$ZIPDIR2/$zfile" ]; then
                if ! cmp -s "$ZIPDIR1/$zfile" "$ZIPDIR2/$zfile"; then
                    found_diff=true
                    echo ""
                    echo "  Difference in: $zfile"
                    diff "$ZIPDIR1/$zfile" "$ZIPDIR2/$zfile" | head -30 || true
                fi
            fi
        done
        
        if [ "$found_diff" = false ]; then
            # Maybe the zip metadata differs, not content
            echo "  (zip file metadata differs, not content - showing hexdump diff)"
            diff <(xxd "$DIR1/$file" | head -20) <(xxd "$DIR2/$file" | head -20) || true
        fi
        
        rm -rf "$ZIPDIR1" "$ZIPDIR2"
    elif [[ "$file" == *.html ]] || [[ "$file" == *.js ]] || [[ "$file" == *.json ]] || [[ "$file" == *.css ]]; then
        # For text files, show the actual diff
        diff "$DIR1/$file" "$DIR2/$file" | head -50 || true
    else
        # For other binary files, show hexdump diff
        echo "(binary file - showing hexdump diff)"
        diff <(xxd "$DIR1/$file" | head -20) <(xxd "$DIR2/$file" | head -20) || true
    fi
    echo ""
done

echo "=== Summary ==="
echo "Total files with differences: ${#DIFF_FILES[@]}"
echo ""
echo "The hexdump shows differences in ZIP file headers at bytes 10-11 (e.g., b758 vs c758)."
echo "These bytes represent the 'last modification time' in DOS format."
echo ""
echo "The actual content (JSON files) inside the ZIPs is identical, but javadoc embeds"
echo "the current system time as file modification timestamps in the ZIP headers."
echo "This makes the -docs.jar non-deterministic even though documentation content is the same."
echo ""
echo "This is controlled by rules_jvm_external's maven_export macro, not rules_scala."
