# Declared inputs for nested Bazel tests. Listing these files in those tests'
# `data` re-keys the tests when the logic changes.
exports_files([
    "macros/bzlmod.bzl",
    "macros/compiler_sources_integrity.bzl",
    "macros/scala_repositories.bzl",
])
