toolchain_type(
    name = "scalafmt_toolchain_type",
    visibility = ["//visibility:public"],
)

filegroup(
    name = "package_sources",
    srcs = glob(["**/*"], allow_empty = True),
    visibility = ["//test/community_build:__pkg__"],
)
