load("@com_google_protobuf//bazel:proto_library.bzl", "proto_library")

proto_library(
    name = "dependency",
    srcs = glob(["*.proto"]),
    strip_import_prefix = "",
    visibility = ["//visibility:public"],
)
