load("//test/expect_build_failure:expect_build_failure.bzl", "expect_build_success_test")

package(default_testonly = 1)

expect_build_success_test(
    name = "proto_source_root",
    target = "//test/proto_source_root/user:user_scala",
)
